---
  - name: copy
    become: true
    copy:
      src:  /root/project/artifact.tar.gz
      dest: /home/ubuntu/artifact.tar.gz 
      

  - name: Start PM2
    become: true
    shell: |
      cd /home/ubuntu/
      tar xzf artifact.tar.gz
      ls
      cd backend
      npm install
      npm run build
      pm2 start npm -- start