---
  - name: Extract artifact.tar.gz file to EC2 Instance 
    become: yes
    unarchive:
      src:  ~/project/artifact.tar.gz
      dest: /home/ubuntu 
      remote_src: no
      mode: 755

  - name: start app 
    become: yes
    shell: |
      cd ~/backend
      npm install
      pm2 stop default
      pm2 start npm -- start
      cd dist
      pm2 start main.js --update-env
