---
  - name: Extract artifact.tar.gz file to EC2 Instance 
    become: true
    unarchive:
      src:  ~/project/artifact.tar.gz
      dest: /home/ubuntu 
      remote_src: no
      mode: 755

  - name: start app 
    become: true
    shell: |
      cd /home/ubuntu/backend
      npm install
      npm run build
      pm2 start npm -- start

