---
  - name: Extract artifact.tar.gz file to EC2 Instance 
    become: yes
    unarchive:
      src:  ~/project/artifact.tar.gz
      dest: /home/ubuntu 
      remote_src: no
      mode: 755

  - name: "executing node"
    become: true
    command: |
      cd /home/ubuntu/backend
      pm2 start npm --name backend -- start
      pm2 ls
