---
  - name: Extract artifact.tar.gz file to EC2 Instance 
    become: yes
    unarchive:
      src:  ~/project/artifact.tar.gz
      dest: /home/ubuntu 
      remote_src: no
      mode: 755
      
  - name: Install packages based on package.json.
    npm:
      path: /home/ubuntu

  - name: start app
    become: yes
    shell: |
      pm2 stop default
      pm2 start npm -- start
